# .travis.yml file for pybooru

# Python version
matrix:
  include:
    - python: '2.7'
      os: linux
      language: python

    - python: '3.3'
      os: linux
      language: python

    - python: '3.4'
      os: linux
      language: python

    - python: '3.5'
      os: linux
      language: python

    - python: '3.6'
      os: linux
      language: python

    # OSX ENV
    - os: osx
      #osx_image: xcode9.3
      env: PYTHON_VERSION=2.7
      language: generic

    - os: osx
      #osx_image: xcode9.3
      env: PYTHON_VERSION=3.6
      language: generic

branches:
    - develop
    - master

install:
    # Install requests and flake8
    - if [ $TRAVIS_OS_NAME == osx ]; then
        pip2 install --user -r requirements.txt flake8;
      else
        pip install -r requirements.txt flake8;
      fi

before_script:
    # Run pylint
    - python -m flake8 pybooru/

script:
    # Run test script, but at the moment is a provisional test
    - python provisional_test.py
