# .travis.yml file for pybooru

# Python version
matrix:
  include:
    - python: '2.7'
      os: linux
      language: python

    - python: '3.5'
      os: linux
      language: python

    - python: '3.6'
      os: linux
      language: python

    - python: '3.7'
      os: linux
      language: python

    - python: '3.8'
      os: linux
      language: python

    # OSX ENV
    - os: osx
      osx_image: xcode9.4
      env: PYTHON_VERSION=2.7
      language: generic

    - os: osx
      osx_image: xcode9.4
      env: PYTHON_VERSION=3.7
      language: generic

branches:
  - master

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      pip install --user pipenv;
      python -m pipenv install --dev;
    else
      pip install pipenv;
      pipenv install --dev;
    fi
  - $PIPENV_VERBOSITY=-1

script:
  # Run test script, but at the moment is a provisional test
  # TODO: configure pylint properly
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      python -m pipenv run pylint --errors-only pybooru/;
      python -m pipenv run python provisional_test.py;
    else
      pylint --errors-only pybooru/ ;
      python provisional_test.py;
    fi
