# AppVeyor recipe

# Not a VS project
build: off

environment:
  matrix:
    # List: https://www.appveyor.com/docs/windows-images-software/#python
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.17"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.4"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.8"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.5"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.0"
      PYTHON_ARCH: "64"

init:
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %HOMEDRIVE%%HOMEPATH%

install:
  - ps: python -W ignore -m pip install --upgrade pip
  - ps: python -W ignore -m pip install pipenv
  - ps: $PIPENV_QUIET="true"
  - pipenv --python %PYTHON_VERSION%
  - pipenv install --dev"

test_script:
  # TODO: configure pylint properly
  - pipenv run pylint --errors-only pybooru\
  # Run test script, but at the moment is a provisional test
  - pipenv run provisional_test.py
